<?php

namespace Sigma\Document;

use Sigma\Element;

class Document extends Element
{
    /**
     * Camelcased class name
     *
     * @var string
     */
    protected $name;

    /**
     * Identifier generated by Elasticsearch
     *
     * @var boolean
     */
    protected $autoId = true;

    /**
     * Auto created and update timestamps
     *
     * @var boolean
     */
    protected $timestamps = true;

    /**
     * Document properties
     *
     * @var array
     */
    protected $properties = [];

    /**
     * Identifier of the document index 
     *
     * @var string
     */
    protected $index;
}
