name: Test Elasticsearch 

on: push

jobs:
  tests:
    runs-on: ubuntu-20.04

    env:
      ELASTICSEARCH_VERSION:
      ELASTICSEARCH_PLUGINS:
      LOCAL_EMBEDDING_URL: http://localhost:7997
      LOCAL_RERANK_URL: http://localhost:7998

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1', 
        # '8.2', '8.3', '8.4'
        ]
        elasticsearch_version: ['7.17.9', '8.17.3']
        stability: [prefer-stable]
        include:
          - php: '8.1'
            flags: "--ignore-platform-req=php"
            stability: prefer-stable

    services:
      es:
        image: docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.elasticsearch_version }}
        ports:
        - 9200:9200
        options: -e="discovery.type=single-node" -e="xpack.security.enabled=false" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
        env:
          ELASTICSEARCH_PLUGINS: "elastiknn"

    name: PHP ${{ matrix.php }} - Elasticsearch ${{ matrix.elasticsearch_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Embeddings Service
        run: |
          docker run -d --name embeddings \
            -p 7997:7997 \
            -e MODEL_ID=BAAI/bge-small-en-v1.5 \
            michaelf34/infinity:latest \
            v2 --model-id BAAI/bge-small-en-v1.5 --port 7997

      - name: Start Reranker Service
        run: |
          docker run -d --name reranker \
            -p 7998:7998 \
            -e MODEL_ID=cross-encoder/ms-marco-MiniLM-L-6-v2 \
            michaelf34/infinity:latest \
            v2 --model-id cross-encoder/ms-marco-MiniLM-L-6-v2 --port 7998

      - name: Wait for AI Services to Start
        run: |
          echo "Waiting for embeddings service..."
          until curl -f http://localhost:7997/health 2>/dev/null; do
            echo "Waiting for embeddings..."
            sleep 5
          done
          echo "Embeddings service is ready!"

          echo "Waiting for reranker service..."
          until curl -f http://localhost:7998/health 2>/dev/null; do
            echo "Waiting for reranker..."
            sleep 5
          done
          echo "Reranker service is ready!"

      - name: Set Elasticsearch Version as GitHub Action ENV Vars
        run: |
          set -e 
          if [[ "${{ matrix.elasticsearch_version }}" == 7* ]]; then
            echo "ELASTICSEARCH_VERSION=7.x" >> $GITHUB_ENV
            echo "ELASTICSEARCH_PLUGINS=elastiknn,elasticsearch-skroutz-greekstemmer,elasticsearch-analysis-greeklish" >> $GITHUB_ENV
          elif [[ "${{ matrix.elasticsearch_version }}" == 8* ]]; then
            echo "ELASTICSEARCH_VERSION=8.x" >> $GITHUB_ENV
            echo "ELASTICSEARCH_PLUGINS=elastiknn" >> $GITHUB_ENV
          fi

      - name: Wait for Elasticsearch to Start
        run: |
          echo "Waiting for Elasticsearch to start..."
          until curl -s http://localhost:9200 | grep "tagline"; do
            sleep 5
          done
          echo "Elasticsearch is ready!"

      - name: Install Plugins
        run: |
          set -e 
          curl -X PUT "http://localhost:9200/_cluster/settings" -H "Content-Type: application/json" -d '{
            "persistent": {
              "action.destructive_requires_name": false
            }
          }'
          declare -a plugins
          plugins+=("https://github.com/alexklibisz/elastiknn/releases/download/${{ matrix.elasticsearch_version }}.0/elastiknn-${{ matrix.elasticsearch_version }}.0.zip")
          plugins+=("https://github.com/sigmie/elasticsearch-skroutz-greekstemmer/releases/download/${{ matrix.elasticsearch_version }}.0/elasticsearch-skroutz-greekstemmer-${{ matrix.elasticsearch_version }}.0.zip")
          plugins+=("https://github.com/sigmie/elasticsearch-analysis-greeklish/releases/download/${{ matrix.elasticsearch_version }}.0/elasticsearch-analysis-greeklish-${{ matrix.elasticsearch_version }}.0.zip")

          for plugin in "${plugins[@]}"; do
            docker exec $(docker ps -q --filter ancestor=docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.elasticsearch_version}}) elasticsearch-plugin install --batch $plugin
          done
          docker restart $(docker ps -q --filter ancestor=docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.elasticsearch_version}})

      - name: Wait for Elasticsearch to Restart
        run: |
          echo "Waiting for Elasticsearch to start..."
          until curl -s http://localhost:9200 | grep "tagline"; do
            sleep 5
          done
          echo "Elasticsearch is ready!"

      - name: Verify Plugin Installation
        run: |
          curl -X GET "http://localhost:9200/_cat/plugins?v"

      - name: Create .env file
        run: touch .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, libxml, mbstring, zip, pcntl, gd,
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}

      - name: Tests
        continue-on-error: ${{ matrix.php > 8 }}
        run: vendor/bin/phpunit -c phpunit.xml

      - uses: codecov/codecov-action@v3
        with:
          files: coverage.xml

      # - name: Static analysis
      #   run: vendor/bin/phpstan analyse --memory-limit=-1
